FROM debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    make perl gcc gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu \
    clang clang-format clang-tools shellcheck \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /src
